### ISSUE TITLE
commands to add

### ISSUE THREAD

**Issue by joesitton** [anthonynguyen/pugbot_ng#20]
- [x] `.ringer`
- [x] `.active`
- [x] `.joinringer`
- [x] `.last`

**Comment by bsdlp** [comment]
is `.ringer` different from `.joinringer`? I assume `.ringer` is the command for requesting ringers, should that be something like `.need <count>` instead?

**Comment by anthonynguyen** [comment]
Probably. Would it be best to let the bot figure it out? I was thinking we'd have the bot query the active PUG at certain intervals, and if a player is missing for enough intervals, then it would call a ringer automatically?

**Comment by bsdlp** [comment]
yeah the bot should be smart enough to figure out the count

**Comment by joesitton** [comment]
what about if you just do `.join ringer` and be placed in a separate queue and when a ringer is needed (from @clearskies idea) it tells the first person in the queue that they can play?

**Comment by bsdlp** [comment]
I would not prefer the ringer queue method because ideally you want a ringer ASAP, which means that if someone joins the queue there's a better chance they will forget/be afk. Then we'll need to go through the ringer timeout period before another ringer is requested. It's probably a better idea to chanmsg that pug <x> needs a ringer.

alternatively, we can create a ringer queue that isn't actually a queue, but simply a list users join to be notified via NOTICE/PRIVMSG when a ringer is needed.

**Comment by joesitton** [comment]
true @fly
